### ISSUE TITLE
Add the ability to supply a connection factory for R2DBC projections

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka-projection#1232]
### Short description

Add a method overload so that [`connFactory`](https://github.com/akka/akka-projection/blob/e956248d81634c8d6b234bf4a3600e2889ffbd94/akka-projection-r2dbc/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala#L54) is supplied instead of generated.

### Details

This will allow a centralization of the factory for tools that centrally create it and inject it as needed.

**Comment by sebastian-alfers** [comment]
I took a look. 

For scaladsl, I think we can just add a new param that can provide an `Option[ConnectionFactory]]` to provide a custom one, using a default value of `None`.

But for javadsl, where we can not use default arguments, it seems to introduce a change where the user has to provide a "none" to indicate the default behavior. Not sure if that is a good idea?

Or am I missing something? Any input would be appreciated.

**Comment by johanandren** [comment]
We can't use default arguments to public API that's problematic for evolution, but we can just add overloads which does the same thing, both in Scala and Java?

**Comment by johanandren** [comment]
Actually, digging slightly deeper, it might be easiest with an `R2dbcProjectionSettings#customConnectionFactory: Option[ConnectionFactory]` that is always `None` if not explicitly set, than handle that everywhere the concrete connection factory is created, I think `R2dbcProjectionSettings` is in scope in all those places. That's less invasive because no method overrides needed, and can be invalidated against other settings if needed (do we support db sharding in r2dbc projections for example, if so that would be a validation failure to combine with custom connection factory).

**Comment by sebastian-alfers** [comment]
> if so that would be a validation failure to combine with custom connection factory

Can't we leave this to the user to understand when using such an advanced feature? We can just make a comment in the docs that they need to be careful?

**Comment by sebastian-alfers** [comment]
Draft pr: https://github.com/akka/akka-projection/pull/1254

**Comment by sebastian-alfers** [comment]
@JustinPihony Do you want to review?

**Comment by JustinPihony** [comment]
LGTM - approved on my end

**Comment by ennru** [comment]
Implemented with
- #1254
