### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#208]
Currently the docs lists all the little pieces that are needed but never really the whole picture. I find that hard to digest and think that it would be good if it instead started with the whole picture.

One idea would be
* moving the "Running a projection" up top after "Use Cases", so that's what you end up starting with
* start that section with some overview text explaining an outline of what we want to do
* then a full code snippet doing all of it
* then sections that talks about the details with little snippets or references to the full sample, and links off to the various options for that part "In this sample we use JDBC but you could also use [a] [b]"

**Comment by patriknw** [comment]
I think we should have a "Getting started guide", using the CQRS sample project. Then the other pages can still be reference docs style with full information about the details.
Related to #169

**Comment by seglo** [comment]
@patriknw Is the idea here to use the CQRS sample project in projections documentation?  Does that mean copying it to the projections `examples` project?  Is there a way to refer to code snippets in other projects?

**Comment by patriknw** [comment]
There is no way to include code outside of the src and that would also be dangerous because the sample project could evolve differently from what we need in the docs. We have to copy it, and we already have some of it: https://github.com/akka/akka-projection/blob/master/examples/src/test/scala/docs/eventsourced/ShoppingCart.scala

We can still refer to the download of the sample project as a template.

**Comment by seglo** [comment]
Completed with #404
