### ISSUE TITLE
Improve documentation around tagging

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#449]
The https://doc.akka.io/docs/akka-projection/current/eventsourced.html#sourceprovider-for-eventsbytag should show how to tag in the entity. `.withTagger` in the `ShoppingCart`.

The https://doc.akka.io/docs/akka-projection/current/running.html#tagging-events-in-eventsourcedbehavior section should also show the actual `.withTagger` in the `ShoppingCart`.

Also link to reference docs for more details https://doc.akka.io/docs/akka/current/typed/persistence.html#tagging

The Getting Started has similar problems and in addition defines the tags in a different way than the other examples. `ShoppingCartTags`. The EventGeneratorApp has `cartBehavior` but would be better to make it look more real with the same kind of `ShoppingCart` as in other examples.

We should also consider moving the `EventGeneratorApp` code to a separate page to avoid the big wall of code of something that is not essential for understanding Projections, but needed for running the example.

Feedback from @WadeWaldron

**Comment by patriknw** [comment]
A difficult balance is that this is part of the reference docs of Projections and not a guide for everything. That guide will be https://github.com/akka/akka-platform-guide and it covers how Event Sourcing and Projections fit together. The tagging is essential for Projections, though so there must be some duplication in the Projections getting started and reference docs.

**Comment by WadeWaldron** [comment]
Incidentally, another issue that I am struggling with as I go through the documentation is that there are different examples of tags in different places. I haven't found anywhere that demonstrates a "best practice" for tagging.

What I mean is, one example shows creating a series of tags like "cart_1", "cart_2", "cart_3". I assume the intent here is to create multiple consumers for these tags so that you can distribute them across a cluster (with sharding perhaps). What I haven't found is an explanation of that or a suggestion of whether its a good practice or not.

Are there common ways that tagging is used? Are there best practices for it?

**Comment by patriknw** [comment]
That is supposed to be described in https://doc.akka.io/docs/akka-projection/current/running.html#tagging-events-in-eventsourcedbehavior

If you want an up to date version of a "full" example I'd recommend https://github.com/akka/akka-platform-guide/tree/main/docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-scala
The tutorial you looked at the other day covers this kind of projections in "Part 5: Projection for queries".
