### ISSUE TITLE
Use testcontainers project for implementations

### ISSUE THREAD

**Issue by seglo** [akka/akka-projection#55]
It would be beneficial to use real underlying datasources for integration testing of implementations (Slick/JDBC, Cassandra, Kafka, etc.) The [testcontainers-java](https://www.testcontainers.org/) allows the developer to automatically orchestrate Docker containers during the lifetime of a test. This has several benefits:

* Does not pollute Java test classpath with "embedded" technologies like embedded Kafka, Cassandra, H2, etc.
* Test multiple implementations when applicable, such as Postgres and MariaDB, or Cassandra and its Datastax enterprise counterpart.
* Run actual datasources that don't have an embedded or mockable Java dependency.

**Comment by patriknw** [comment]
I think that would be excellent here. Maybe you can start by setting up one for Cassandra, based on my PR https://github.com/akka/akka-projection/pull/54

Next would be Kafka.

Different databases for JDBC would also be good, but that can be last priority since we have a way of testing that at the moment with the inmem db.

**Comment by patriknw** [comment]
One important aspect is that it's reusing the same container for all tests to avoid the slowdown of starting/stopping the container for each test.

**Comment by patriknw** [comment]
As a start I'm launching Cassandra with Docker in Travis. Same approach as in akka-persistence-cassandra. e940458950b626d0b7bf47b89b3ef8a52f89f3e8
